### ISSUE TITLE
Summary page chart

### ISSUE THREAD

**Issue by johdyn** [johdyn/capstoneNF2021#5]
## Value statement - a requirement, not a solution
As a **user**
I need **to be able to see my total CO2 emission and emission divided on transport form (car, plane) for different periods: Week, month, year**
so that **I have an overview of my CO2 emissions over time**
As a **user**
I need **to be able to set a personal CO2 limit for a given time period**
so that **I can see how much I exceed my limit**

## Acceptance criteria
- [x] User can see total emission
- [ ] User can see the emission of the four transport forms in a Pie chart with percentages
- [ ] User can set a personal CO2 emission limit for the year (starting from the earliest date)
## Tasks
- [x] Create a component which renders a Pie chart that shows car/plane/train/bus CO2 with percentages and in different colors
- [x] Component is updated every time a trip item is saved to or removed from local storage
- [ ] The user can type in the personal CO2 goal and it is calculated how much CO2 remains/how much CO2 the goal is exceeded already

## Size
Large
